// <auto-generated />
using System;
using Aegis.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aegis.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821175322_tenant_emp_rel")]
    partial class tenant_emp_rel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Aegis.Model.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Aegis.Model.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Aegis.Model.Employee.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Aegis.Model.Master.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ApplicationRoles");
                });

            modelBuilder.Entity("Aegis.Model.Master.ApplicationRolePermisson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationRoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FeaturePermissionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationRoleId");

                    b.HasIndex("FeaturePermissionId");

                    b.ToTable("ApplicationRolePermissons");
                });

            modelBuilder.Entity("Aegis.Model.Master.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ce21b3c-baf9-4ebe-9219-ff08cae22f1b"),
                            Description = "Create, view, update and manage leads.",
                            IsActive = false,
                            Key = "lead_management",
                            ModuleId = new Guid("6b4c01ba-8aa4-47ed-8ea2-1dc7fa5cd638"),
                            Name = "Lead Management"
                        },
                        new
                        {
                            Id = new Guid("6327f4df-4a2e-4268-962a-481c1ab9b93e"),
                            Description = "Capture leads from different sources.",
                            IsActive = false,
                            Key = "lead_capture",
                            ModuleId = new Guid("6b4c01ba-8aa4-47ed-8ea2-1dc7fa5cd638"),
                            Name = "Lead Capture"
                        },
                        new
                        {
                            Id = new Guid("b14e3341-795c-416a-9d65-d25f4de688b0"),
                            Description = "Manage lead sources and acquisition channels.",
                            IsActive = false,
                            Key = "lead_sources",
                            ModuleId = new Guid("6b4c01ba-8aa4-47ed-8ea2-1dc7fa5cd638"),
                            Name = "Lead Sources"
                        },
                        new
                        {
                            Id = new Guid("a767bedb-1089-4a1a-b5d2-03205885262a"),
                            Description = "Qualify leads based on business criteria.",
                            IsActive = false,
                            Key = "lead_qualification",
                            ModuleId = new Guid("6b4c01ba-8aa4-47ed-8ea2-1dc7fa5cd638"),
                            Name = "Lead Qualification"
                        },
                        new
                        {
                            Id = new Guid("e9f2a460-0cac-4153-83b3-f0ec1a9c4c01"),
                            Description = "Score and prioritize leads.",
                            IsActive = false,
                            Key = "lead_scoring",
                            ModuleId = new Guid("6b4c01ba-8aa4-47ed-8ea2-1dc7fa5cd638"),
                            Name = "Lead Scoring"
                        },
                        new
                        {
                            Id = new Guid("1a7b5f4a-68bb-48f7-b4b9-d8383ae23d4c"),
                            Description = "Convert qualified leads into opportunities and contacts.",
                            IsActive = false,
                            Key = "lead_conversion",
                            ModuleId = new Guid("6b4c01ba-8aa4-47ed-8ea2-1dc7fa5cd638"),
                            Name = "Lead Conversion"
                        },
                        new
                        {
                            Id = new Guid("ee528c96-89ee-4728-9f27-ade7a179d405"),
                            Description = "Detect and manage duplicate leads.",
                            IsActive = false,
                            Key = "lead_duplicate_detection",
                            ModuleId = new Guid("6b4c01ba-8aa4-47ed-8ea2-1dc7fa5cd638"),
                            Name = "Duplicate Detection"
                        },
                        new
                        {
                            Id = new Guid("50ab36d8-5211-495d-88a9-db3de9d7fd2f"),
                            Description = "Create, view, update and manage opportunities.",
                            IsActive = false,
                            Key = "opportunity_management",
                            ModuleId = new Guid("a009cd33-faf4-4e8a-bde4-fc2562c2198e"),
                            Name = "Opportunity Management"
                        },
                        new
                        {
                            Id = new Guid("775c0750-9dae-4bf7-a5e0-c77c50d0866a"),
                            Description = "Manage opportunity stages and progression.",
                            IsActive = false,
                            Key = "opportunity_stages",
                            ModuleId = new Guid("a009cd33-faf4-4e8a-bde4-fc2562c2198e"),
                            Name = "Opportunity Stages"
                        },
                        new
                        {
                            Id = new Guid("94b04436-fccd-46ae-847f-04edfc5da6c7"),
                            Description = "Manage opportunity value and expected revenue.",
                            IsActive = false,
                            Key = "opportunity_value",
                            ModuleId = new Guid("a009cd33-faf4-4e8a-bde4-fc2562c2198e"),
                            Name = "Opportunity Value"
                        },
                        new
                        {
                            Id = new Guid("450a0e10-1f35-4883-b2a2-1cc45110b6af"),
                            Description = "Manage probability of opportunity closure.",
                            IsActive = false,
                            Key = "opportunity_probability",
                            ModuleId = new Guid("a009cd33-faf4-4e8a-bde4-fc2562c2198e"),
                            Name = "Opportunity Probability"
                        },
                        new
                        {
                            Id = new Guid("2b3a902c-4357-4f28-ad7a-474ed9623981"),
                            Description = "Forecast opportunity revenue and expected closures.",
                            IsActive = false,
                            Key = "opportunity_forecasting",
                            ModuleId = new Guid("a009cd33-faf4-4e8a-bde4-fc2562c2198e"),
                            Name = "Opportunity Forecasting"
                        },
                        new
                        {
                            Id = new Guid("b528b3e4-ca9b-4e0a-adfe-32f5722a6992"),
                            Description = "Manage activities related to opportunities.",
                            IsActive = false,
                            Key = "opportunity_activities",
                            ModuleId = new Guid("a009cd33-faf4-4e8a-bde4-fc2562c2198e"),
                            Name = "Opportunity Activities"
                        },
                        new
                        {
                            Id = new Guid("ad89af4a-c7f3-45a3-8426-df1cff0f4f21"),
                            Description = "Manage requirements associated with opportunities.",
                            IsActive = false,
                            Key = "opportunity_requirements",
                            ModuleId = new Guid("a009cd33-faf4-4e8a-bde4-fc2562c2198e"),
                            Name = "Opportunity Requirements"
                        },
                        new
                        {
                            Id = new Guid("88293270-5873-4b8f-a4e4-1065ce494ae0"),
                            Description = "Create, view, update and manage contacts.",
                            IsActive = false,
                            Key = "contact_management",
                            ModuleId = new Guid("1f65bb9f-4f28-4530-99f1-e20cbaf9b344"),
                            Name = "Contact Management"
                        },
                        new
                        {
                            Id = new Guid("27a56e31-5a1a-4992-b01f-1e309220e9cb"),
                            Description = "Manage relationships between contacts and business records.",
                            IsActive = false,
                            Key = "contact_relationships",
                            ModuleId = new Guid("1f65bb9f-4f28-4530-99f1-e20cbaf9b344"),
                            Name = "Contact Relationships"
                        },
                        new
                        {
                            Id = new Guid("f974510b-51b1-4e1b-9626-c288ee965dee"),
                            Description = "Manage activities related to contacts.",
                            IsActive = false,
                            Key = "contact_activities",
                            ModuleId = new Guid("1f65bb9f-4f28-4530-99f1-e20cbaf9b344"),
                            Name = "Contact Activities"
                        },
                        new
                        {
                            Id = new Guid("c84e8997-8763-410f-b5a9-80145d12515c"),
                            Description = "Manage documents associated with contacts.",
                            IsActive = false,
                            Key = "contact_documents",
                            ModuleId = new Guid("1f65bb9f-4f28-4530-99f1-e20cbaf9b344"),
                            Name = "Contact Documents"
                        },
                        new
                        {
                            Id = new Guid("160bd4df-d18e-405d-989b-b5bdba1e8528"),
                            Description = "View the history and timeline of contact interactions.",
                            IsActive = false,
                            Key = "contact_timeline",
                            ModuleId = new Guid("1f65bb9f-4f28-4530-99f1-e20cbaf9b344"),
                            Name = "Contact Timeline"
                        },
                        new
                        {
                            Id = new Guid("7d41fe16-f08f-48a8-a7e1-0873572f8a90"),
                            Description = "Create, view and manage sales pipelines.",
                            IsActive = false,
                            Key = "pipeline_management",
                            ModuleId = new Guid("c50e290a-672b-430a-8dad-58fbb574415a"),
                            Name = "Pipeline Management"
                        },
                        new
                        {
                            Id = new Guid("5f2bad79-cef6-4a48-bd7e-d935c767abcf"),
                            Description = "Configure and manage pipeline stages.",
                            IsActive = false,
                            Key = "pipeline_stages",
                            ModuleId = new Guid("c50e290a-672b-430a-8dad-58fbb574415a"),
                            Name = "Pipeline Stages"
                        },
                        new
                        {
                            Id = new Guid("ccd21a8b-e3c7-49ae-80a6-284dc1317b3d"),
                            Description = "Manage multiple sales pipelines.",
                            IsActive = false,
                            Key = "multiple_pipelines",
                            ModuleId = new Guid("c50e290a-672b-430a-8dad-58fbb574415a"),
                            Name = "Multiple Pipelines"
                        },
                        new
                        {
                            Id = new Guid("04f070f0-4449-47c4-8f10-e9eb319cc4d1"),
                            Description = "Track changes and movement across pipeline stages.",
                            IsActive = false,
                            Key = "pipeline_history",
                            ModuleId = new Guid("c50e290a-672b-430a-8dad-58fbb574415a"),
                            Name = "Pipeline History"
                        },
                        new
                        {
                            Id = new Guid("113179e6-2038-4ba4-ab22-47e131e80b75"),
                            Description = "View and manage pipeline records using a Kanban board.",
                            IsActive = false,
                            Key = "pipeline_kanban",
                            ModuleId = new Guid("c50e290a-672b-430a-8dad-58fbb574415a"),
                            Name = "Pipeline Kanban"
                        },
                        new
                        {
                            Id = new Guid("27f42f6e-dbd4-4285-b366-9f7cd2bf43d8"),
                            Description = "Forecast pipeline performance and expected revenue.",
                            IsActive = false,
                            Key = "pipeline_forecasting",
                            ModuleId = new Guid("c50e290a-672b-430a-8dad-58fbb574415a"),
                            Name = "Pipeline Forecasting"
                        },
                        new
                        {
                            Id = new Guid("26414dc5-a6ba-4825-87c1-db1636873ce8"),
                            Description = "Create, view, update and manage activities.",
                            IsActive = false,
                            Key = "activity_management",
                            ModuleId = new Guid("8e4ecd5b-f2e4-4d73-baf5-910508e4ee5a"),
                            Name = "Activity Management"
                        },
                        new
                        {
                            Id = new Guid("a104ef97-1766-45af-bd54-b9df4118d165"),
                            Description = "Create and manage call activities.",
                            IsActive = false,
                            Key = "call_activity",
                            ModuleId = new Guid("8e4ecd5b-f2e4-4d73-baf5-910508e4ee5a"),
                            Name = "Call Activity"
                        },
                        new
                        {
                            Id = new Guid("1bd1b732-4d31-4be4-a23a-e2b08619bcc2"),
                            Description = "Create and manage email activities.",
                            IsActive = false,
                            Key = "email_activity",
                            ModuleId = new Guid("8e4ecd5b-f2e4-4d73-baf5-910508e4ee5a"),
                            Name = "Email Activity"
                        },
                        new
                        {
                            Id = new Guid("b54fe2e2-3563-48e8-aeda-509e52030007"),
                            Description = "Create and manage meeting activities.",
                            IsActive = false,
                            Key = "meeting_activity",
                            ModuleId = new Guid("8e4ecd5b-f2e4-4d73-baf5-910508e4ee5a"),
                            Name = "Meeting Activity"
                        },
                        new
                        {
                            Id = new Guid("afe14019-14bb-4804-aa35-b78b7fe378f4"),
                            Description = "Create and manage notes and activity notes.",
                            IsActive = false,
                            Key = "note_activity",
                            ModuleId = new Guid("8e4ecd5b-f2e4-4d73-baf5-910508e4ee5a"),
                            Name = "Note Activity"
                        },
                        new
                        {
                            Id = new Guid("be652534-efba-466a-98a7-372ce2846460"),
                            Description = "Create and manage custom activity types.",
                            IsActive = false,
                            Key = "custom_activity",
                            ModuleId = new Guid("8e4ecd5b-f2e4-4d73-baf5-910508e4ee5a"),
                            Name = "Custom Activity"
                        },
                        new
                        {
                            Id = new Guid("6b97f241-5b4f-4e79-a769-d3291f31dc19"),
                            Description = "Create, view, update and manage tasks.",
                            IsActive = false,
                            Key = "task_management",
                            ModuleId = new Guid("78d7bee8-a5d0-4689-91f7-2b350f22696a"),
                            Name = "Task Management"
                        },
                        new
                        {
                            Id = new Guid("3c2e8541-4273-42c3-bfef-5492454edeee"),
                            Description = "Assign tasks to users and teams.",
                            IsActive = false,
                            Key = "task_assignment",
                            ModuleId = new Guid("78d7bee8-a5d0-4689-91f7-2b350f22696a"),
                            Name = "Task Assignment"
                        },
                        new
                        {
                            Id = new Guid("ca63a567-711a-4d00-a8dc-4377aed508c6"),
                            Description = "Manage task priorities.",
                            IsActive = false,
                            Key = "task_priority",
                            ModuleId = new Guid("78d7bee8-a5d0-4689-91f7-2b350f22696a"),
                            Name = "Task Priority"
                        },
                        new
                        {
                            Id = new Guid("ab456a9c-806e-4f0c-92d9-1e8e136f5e5f"),
                            Description = "Manage task statuses.",
                            IsActive = false,
                            Key = "task_status",
                            ModuleId = new Guid("78d7bee8-a5d0-4689-91f7-2b350f22696a"),
                            Name = "Task Status"
                        },
                        new
                        {
                            Id = new Guid("569d198b-93e8-490f-a419-ec604c23487a"),
                            Description = "Manage checklists within tasks.",
                            IsActive = false,
                            Key = "task_checklist",
                            ModuleId = new Guid("78d7bee8-a5d0-4689-91f7-2b350f22696a"),
                            Name = "Task Checklist"
                        },
                        new
                        {
                            Id = new Guid("b4e7c404-78f8-4a9d-8471-6174dd8e5ce3"),
                            Description = "Create, view, update and manage meetings.",
                            IsActive = false,
                            Key = "meeting_management",
                            ModuleId = new Guid("bf21b75b-7ea6-4ca9-b69b-120dc9eba6fc"),
                            Name = "Meeting Management"
                        },
                        new
                        {
                            Id = new Guid("491e70af-d8bc-41ad-983c-0c38b24cebb5"),
                            Description = "Manage meeting attendees and participants.",
                            IsActive = false,
                            Key = "meeting_attendees",
                            ModuleId = new Guid("bf21b75b-7ea6-4ca9-b69b-120dc9eba6fc"),
                            Name = "Meeting Attendees"
                        },
                        new
                        {
                            Id = new Guid("7e730dd8-42f3-4382-8ff2-a5b6b042630d"),
                            Description = "Create and manage meeting agendas.",
                            IsActive = false,
                            Key = "meeting_agenda",
                            ModuleId = new Guid("bf21b75b-7ea6-4ca9-b69b-120dc9eba6fc"),
                            Name = "Meeting Agenda"
                        },
                        new
                        {
                            Id = new Guid("48795578-ec33-4f11-b620-c990a79a0bcd"),
                            Description = "Record and manage meeting notes.",
                            IsActive = false,
                            Key = "meeting_notes",
                            ModuleId = new Guid("bf21b75b-7ea6-4ca9-b69b-120dc9eba6fc"),
                            Name = "Meeting Notes"
                        },
                        new
                        {
                            Id = new Guid("2e54a66d-9100-4dc1-8cf2-4db40c4a927e"),
                            Description = "Configure reminders for scheduled meetings.",
                            IsActive = false,
                            Key = "meeting_reminders",
                            ModuleId = new Guid("bf21b75b-7ea6-4ca9-b69b-120dc9eba6fc"),
                            Name = "Meeting Reminders"
                        },
                        new
                        {
                            Id = new Guid("5ca16678-e0d3-4bf4-a4fe-36cd965526a8"),
                            Description = "Create, view, update and manage site visits.",
                            IsActive = false,
                            Key = "site_visit_management",
                            ModuleId = new Guid("0a539ca7-0233-49f9-b969-c841f7d3c43b"),
                            Name = "Site Visit Management"
                        },
                        new
                        {
                            Id = new Guid("62e0172e-32d8-4d49-b680-3dea19c05281"),
                            Description = "Record site visit check-in and check-out.",
                            IsActive = false,
                            Key = "site_visit_checkin",
                            ModuleId = new Guid("0a539ca7-0233-49f9-b969-c841f7d3c43b"),
                            Name = "Site Visit Check-in"
                        },
                        new
                        {
                            Id = new Guid("e0e0dcac-9dda-4ba1-82b5-94629f54dc08"),
                            Description = "Upload and manage photos and media from site visits.",
                            IsActive = false,
                            Key = "site_visit_media",
                            ModuleId = new Guid("0a539ca7-0233-49f9-b969-c841f7d3c43b"),
                            Name = "Site Visit Media"
                        },
                        new
                        {
                            Id = new Guid("128b4c10-2bd0-4f30-971c-6f51e3891eb7"),
                            Description = "Record notes and observations from site visits.",
                            IsActive = false,
                            Key = "site_visit_notes",
                            ModuleId = new Guid("0a539ca7-0233-49f9-b969-c841f7d3c43b"),
                            Name = "Site Visit Notes"
                        },
                        new
                        {
                            Id = new Guid("19c4c6af-fd77-4b97-99ee-de1583dcdb38"),
                            Description = "Manage checklists for site visits.",
                            IsActive = false,
                            Key = "site_visit_checklists",
                            ModuleId = new Guid("0a539ca7-0233-49f9-b969-c841f7d3c43b"),
                            Name = "Site Visit Checklists"
                        },
                        new
                        {
                            Id = new Guid("d5ca37f4-5a2d-44f2-8415-62aeb2d58893"),
                            Description = "Manage follow-up actions after site visits.",
                            IsActive = false,
                            Key = "site_visit_followup",
                            ModuleId = new Guid("0a539ca7-0233-49f9-b969-c841f7d3c43b"),
                            Name = "Site Visit Follow-up"
                        },
                        new
                        {
                            Id = new Guid("fecbedae-c392-499b-bc9c-ac9dc0a23eaf"),
                            Description = "Create, view, update and manage requirements.",
                            IsActive = false,
                            Key = "requirement_management",
                            ModuleId = new Guid("97a3673c-5760-448a-b248-e3688ad193fb"),
                            Name = "Requirement Management"
                        },
                        new
                        {
                            Id = new Guid("922624d0-7daf-4917-a535-61885a6d32f1"),
                            Description = "Create and manage requirement templates.",
                            IsActive = false,
                            Key = "requirement_templates",
                            ModuleId = new Guid("97a3673c-5760-448a-b248-e3688ad193fb"),
                            Name = "Requirement Templates"
                        },
                        new
                        {
                            Id = new Guid("5d3033e0-7909-4bef-b920-ed6a4c0f4764"),
                            Description = "Organize requirements into sections.",
                            IsActive = false,
                            Key = "requirement_sections",
                            ModuleId = new Guid("97a3673c-5760-448a-b248-e3688ad193fb"),
                            Name = "Requirement Sections"
                        },
                        new
                        {
                            Id = new Guid("17e69f35-bf9a-4b68-815a-16ab7d8da183"),
                            Description = "Create and manage requirement questions.",
                            IsActive = false,
                            Key = "requirement_questions",
                            ModuleId = new Guid("97a3673c-5760-448a-b248-e3688ad193fb"),
                            Name = "Requirement Questions"
                        },
                        new
                        {
                            Id = new Guid("e1900440-3625-41ed-bce6-eec1f924d3df"),
                            Description = "Capture and manage responses to requirements.",
                            IsActive = false,
                            Key = "requirement_responses",
                            ModuleId = new Guid("97a3673c-5760-448a-b248-e3688ad193fb"),
                            Name = "Requirement Responses"
                        },
                        new
                        {
                            Id = new Guid("d39f9687-8482-4fba-adf2-b269a09400e7"),
                            Description = "Upload and manage requirement attachments.",
                            IsActive = false,
                            Key = "requirement_attachments",
                            ModuleId = new Guid("97a3673c-5760-448a-b248-e3688ad193fb"),
                            Name = "Requirement Attachments"
                        },
                        new
                        {
                            Id = new Guid("b837a859-ed3d-4c03-95a1-72864e4fb2eb"),
                            Description = "Create, view, update and manage documents.",
                            IsActive = false,
                            Key = "document_management",
                            ModuleId = new Guid("c6167d9f-0c7f-4271-a325-cbbcb42c0298"),
                            Name = "Document Management"
                        },
                        new
                        {
                            Id = new Guid("6030081d-3ab0-4f5d-a477-b357cfc7f6b6"),
                            Description = "Upload and manage documents.",
                            IsActive = false,
                            Key = "document_upload",
                            ModuleId = new Guid("c6167d9f-0c7f-4271-a325-cbbcb42c0298"),
                            Name = "Document Upload"
                        },
                        new
                        {
                            Id = new Guid("2aa7e974-0721-4837-8c4c-4c6f35b565a7"),
                            Description = "Manage document versions and revisions.",
                            IsActive = false,
                            Key = "document_versioning",
                            ModuleId = new Guid("c6167d9f-0c7f-4271-a325-cbbcb42c0298"),
                            Name = "Document Versioning"
                        },
                        new
                        {
                            Id = new Guid("b4ae0775-f77c-45bd-8329-621f515bb9d8"),
                            Description = "Share documents with authorized users.",
                            IsActive = false,
                            Key = "document_sharing",
                            ModuleId = new Guid("c6167d9f-0c7f-4271-a325-cbbcb42c0298"),
                            Name = "Document Sharing"
                        },
                        new
                        {
                            Id = new Guid("01a7613f-e840-4932-a3da-5cdafeb43198"),
                            Description = "Create, view, update and manage campaigns.",
                            IsActive = false,
                            Key = "campaign_management",
                            ModuleId = new Guid("93d57136-92fc-4a0c-9f36-9fd9f85e23b5"),
                            Name = "Campaign Management"
                        },
                        new
                        {
                            Id = new Guid("932f5a14-0cc3-4012-b030-926578c48017"),
                            Description = "Define and manage campaign audiences.",
                            IsActive = false,
                            Key = "campaign_audiences",
                            ModuleId = new Guid("93d57136-92fc-4a0c-9f36-9fd9f85e23b5"),
                            Name = "Campaign Audiences"
                        },
                        new
                        {
                            Id = new Guid("7ff9cbed-25e1-4bcb-adee-391be9e558e1"),
                            Description = "Manage campaign sources and acquisition channels.",
                            IsActive = false,
                            Key = "campaign_sources",
                            ModuleId = new Guid("93d57136-92fc-4a0c-9f36-9fd9f85e23b5"),
                            Name = "Campaign Sources"
                        },
                        new
                        {
                            Id = new Guid("2353aac8-0935-423d-8ee9-b6981f30111a"),
                            Description = "Track campaign attribution and lead sources.",
                            IsActive = false,
                            Key = "campaign_attribution",
                            ModuleId = new Guid("93d57136-92fc-4a0c-9f36-9fd9f85e23b5"),
                            Name = "Campaign Attribution"
                        },
                        new
                        {
                            Id = new Guid("bb7972f1-63b0-4c6f-859c-7bf28abf98fc"),
                            Description = "Analyze campaign performance and results.",
                            IsActive = false,
                            Key = "campaign_performance",
                            ModuleId = new Guid("93d57136-92fc-4a0c-9f36-9fd9f85e23b5"),
                            Name = "Campaign Performance"
                        },
                        new
                        {
                            Id = new Guid("6f25bf12-7b11-44bc-aecc-3f03b9567bd8"),
                            Description = "Create and configure reports.",
                            IsActive = false,
                            Key = "report_builder",
                            ModuleId = new Guid("82d77160-b060-480d-9d22-244a3b011b8b"),
                            Name = "Report Builder"
                        },
                        new
                        {
                            Id = new Guid("83e49858-6246-4b88-b9f3-36fe5021544c"),
                            Description = "Filter report data using configurable criteria.",
                            IsActive = false,
                            Key = "report_filters",
                            ModuleId = new Guid("82d77160-b060-480d-9d22-244a3b011b8b"),
                            Name = "Report Filters"
                        },
                        new
                        {
                            Id = new Guid("c3fe64f5-1604-4d26-9477-a0039aa58004"),
                            Description = "Group report data by selected fields.",
                            IsActive = false,
                            Key = "report_grouping",
                            ModuleId = new Guid("82d77160-b060-480d-9d22-244a3b011b8b"),
                            Name = "Report Grouping"
                        },
                        new
                        {
                            Id = new Guid("9d31cf55-8f81-4ff8-9548-acf8e6ab31a4"),
                            Description = "Display report data using charts and visualizations.",
                            IsActive = false,
                            Key = "report_charts",
                            ModuleId = new Guid("82d77160-b060-480d-9d22-244a3b011b8b"),
                            Name = "Report Charts"
                        },
                        new
                        {
                            Id = new Guid("11e87daf-0b2d-474f-91f8-1f639529bcac"),
                            Description = "Generate reports related to pipeline performance.",
                            IsActive = false,
                            Key = "pipeline_reports",
                            ModuleId = new Guid("82d77160-b060-480d-9d22-244a3b011b8b"),
                            Name = "Pipeline Reports"
                        },
                        new
                        {
                            Id = new Guid("83144137-5268-4bc5-953f-df5223933abb"),
                            Description = "Generate reports for lead and opportunity conversions.",
                            IsActive = false,
                            Key = "conversion_reports",
                            ModuleId = new Guid("82d77160-b060-480d-9d22-244a3b011b8b"),
                            Name = "Conversion Reports"
                        },
                        new
                        {
                            Id = new Guid("06a470df-66d0-46e3-a7e4-407be3c6205f"),
                            Description = "Generate reports for sales activities.",
                            IsActive = false,
                            Key = "activity_reports",
                            ModuleId = new Guid("82d77160-b060-480d-9d22-244a3b011b8b"),
                            Name = "Activity Reports"
                        },
                        new
                        {
                            Id = new Guid("babc7309-b920-41ea-b3fa-57957a683c3e"),
                            Description = "Generate reports for team performance.",
                            IsActive = false,
                            Key = "team_reports",
                            ModuleId = new Guid("82d77160-b060-480d-9d22-244a3b011b8b"),
                            Name = "Team Reports"
                        },
                        new
                        {
                            Id = new Guid("0cc30bd0-22a2-49f6-8bb2-4747283a5b63"),
                            Description = "Export reports in supported formats.",
                            IsActive = false,
                            Key = "report_export",
                            ModuleId = new Guid("82d77160-b060-480d-9d22-244a3b011b8b"),
                            Name = "Report Export"
                        },
                        new
                        {
                            Id = new Guid("4a0882ae-2e67-4484-8f4b-c0954b730364"),
                            Description = "Schedule reports for automatic generation and delivery.",
                            IsActive = false,
                            Key = "scheduled_reports",
                            ModuleId = new Guid("82d77160-b060-480d-9d22-244a3b011b8b"),
                            Name = "Scheduled Reports"
                        },
                        new
                        {
                            Id = new Guid("d84def16-0452-4869-bff8-c7e8578223b2"),
                            Description = "Create, view and manage notifications.",
                            IsActive = false,
                            Key = "notification_management",
                            ModuleId = new Guid("fe25290f-1402-4401-8933-c9aad35dfaec"),
                            Name = "Notification Management"
                        },
                        new
                        {
                            Id = new Guid("e3252074-231b-49f3-8286-1fb2220c0c85"),
                            Description = "Notify users when records or tasks are assigned.",
                            IsActive = false,
                            Key = "assignment_notifications",
                            ModuleId = new Guid("fe25290f-1402-4401-8933-c9aad35dfaec"),
                            Name = "Assignment Notifications"
                        },
                        new
                        {
                            Id = new Guid("6eb3c2c6-cf82-4b7d-9aed-e41c49b62741"),
                            Description = "Manage reminders for upcoming activities and tasks.",
                            IsActive = false,
                            Key = "reminder_notifications",
                            ModuleId = new Guid("fe25290f-1402-4401-8933-c9aad35dfaec"),
                            Name = "Reminder Notifications"
                        },
                        new
                        {
                            Id = new Guid("9e70fec6-9a25-48a2-b21a-cce5c17c7d3e"),
                            Description = "Notify users when they are mentioned in records or activities.",
                            IsActive = false,
                            Key = "mention_notifications",
                            ModuleId = new Guid("fe25290f-1402-4401-8933-c9aad35dfaec"),
                            Name = "Mention Notifications"
                        });
                });

            modelBuilder.Entity("Aegis.Model.Master.FeaturePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("FeaturePermissions");
                });

            modelBuilder.Entity("Aegis.Model.Master.JobRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("JobRoles");
                });

            modelBuilder.Entity("Aegis.Model.Master.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b4c01ba-8aa4-47ed-8ea2-1dc7fa5cd638"),
                            Description = "Manage potential customers and business opportunities.",
                            Key = "leads",
                            Name = "Leads"
                        },
                        new
                        {
                            Id = new Guid("a009cd33-faf4-4e8a-bde4-fc2562c2198e"),
                            Description = "Manage qualified business opportunities through their lifecycle.",
                            Key = "opportunities",
                            Name = "Opportunities"
                        },
                        new
                        {
                            Id = new Guid("1f65bb9f-4f28-4530-99f1-e20cbaf9b344"),
                            Description = "Manage people and customer relationships.",
                            Key = "contacts",
                            Name = "Contacts"
                        },
                        new
                        {
                            Id = new Guid("c50e290a-672b-430a-8dad-58fbb574415a"),
                            Description = "Manage business pipelines, stages and opportunity progression.",
                            Key = "pipeline",
                            Name = "Pipeline"
                        },
                        new
                        {
                            Id = new Guid("8e4ecd5b-f2e4-4d73-baf5-910508e4ee5a"),
                            Description = "Track interactions and business activities.",
                            Key = "activities",
                            Name = "Activities"
                        },
                        new
                        {
                            Id = new Guid("78d7bee8-a5d0-4689-91f7-2b350f22696a"),
                            Description = "Manage assigned work and follow-up activities.",
                            Key = "tasks",
                            Name = "Tasks"
                        },
                        new
                        {
                            Id = new Guid("bf21b75b-7ea6-4ca9-b69b-120dc9eba6fc"),
                            Description = "Schedule and manage business meetings.",
                            Key = "meetings",
                            Name = "Meetings"
                        },
                        new
                        {
                            Id = new Guid("0a539ca7-0233-49f9-b969-c841f7d3c43b"),
                            Description = "Manage field visits and customer visits.",
                            Key = "site_visits",
                            Name = "Site Visits"
                        },
                        new
                        {
                            Id = new Guid("97a3673c-5760-448a-b248-e3688ad193fb"),
                            Description = "Capture and manage business and customer requirements.",
                            Key = "requirements",
                            Name = "Requirements"
                        },
                        new
                        {
                            Id = new Guid("c6167d9f-0c7f-4271-a325-cbbcb42c0298"),
                            Description = "Manage documents associated with CRM records.",
                            Key = "documents",
                            Name = "Documents"
                        },
                        new
                        {
                            Id = new Guid("93d57136-92fc-4a0c-9f36-9fd9f85e23b5"),
                            Description = "Manage campaigns and lead acquisition activities.",
                            Key = "campaigns",
                            Name = "Campaigns"
                        },
                        new
                        {
                            Id = new Guid("82d77160-b060-480d-9d22-244a3b011b8b"),
                            Description = "Analyze CRM data and business performance.",
                            Key = "reports",
                            Name = "Reports"
                        },
                        new
                        {
                            Id = new Guid("fe25290f-1402-4401-8933-c9aad35dfaec"),
                            Description = "Manage CRM notifications and reminders.",
                            Key = "notifications",
                            Name = "Notifications"
                        });
                });

            modelBuilder.Entity("Aegis.Model.TenantModels.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DomainName")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSystemTenant")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OnboardingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SubscriptionPlanId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Aegis.Model.Auth.RefreshToken", b =>
                {
                    b.HasOne("Aegis.Model.Auth.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aegis.Model.Employee.Employee", b =>
                {
                    b.HasOne("Aegis.Model.TenantModels.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aegis.Model.Auth.ApplicationUser", "User")
                        .WithOne("Employee")
                        .HasForeignKey("Aegis.Model.Employee.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aegis.Model.Master.ApplicationRole", b =>
                {
                    b.HasOne("Aegis.Model.TenantModels.Tenant", "Tenant")
                        .WithMany("ApplicationRoles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Aegis.Model.Master.ApplicationRolePermisson", b =>
                {
                    b.HasOne("Aegis.Model.Master.ApplicationRole", "ApplicationRole")
                        .WithMany()
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aegis.Model.Master.FeaturePermission", "FeaturePermission")
                        .WithMany()
                        .HasForeignKey("FeaturePermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationRole");

                    b.Navigation("FeaturePermission");
                });

            modelBuilder.Entity("Aegis.Model.Master.Feature", b =>
                {
                    b.HasOne("Aegis.Model.Master.Module", "Module")
                        .WithMany("Features")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Aegis.Model.Master.FeaturePermission", b =>
                {
                    b.HasOne("Aegis.Model.Master.Feature", "Feature")
                        .WithMany("FeaturePermissions")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Aegis.Model.Master.JobRole", b =>
                {
                    b.HasOne("Aegis.Model.TenantModels.Tenant", "Tenant")
                        .WithMany("JobRoles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Aegis.Model.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Aegis.Model.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aegis.Model.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Aegis.Model.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aegis.Model.Auth.ApplicationUser", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Aegis.Model.Master.Feature", b =>
                {
                    b.Navigation("FeaturePermissions");
                });

            modelBuilder.Entity("Aegis.Model.Master.Module", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("Aegis.Model.TenantModels.Tenant", b =>
                {
                    b.Navigation("ApplicationRoles");

                    b.Navigation("JobRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
